# Generated by Django 4.2.7 on 2026-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('partition_key', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('publish_attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'outbox_event',
                'indexes': [models.Index(fields=['published_at', 'id'], name='outbox_unpublished_idx')],
            },
        ),
    ]
