apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: classic-models-api
  namespace: classic-models
  labels:
    app.kubernetes.io/name: classic-models-api
    app.kubernetes.io/instance: classic-models-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: classic-models-api
spec:
  # host: classic-models-api.apps.<cluster-domain>   # set explicitly, or omit to let OCP assign one
  to:
    kind: Service
    name: classic-models-api
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
