apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-secret.yaml
  - 02-configmap.yaml
  - 03-deployment.yaml
  - 04-service.yaml
  - 05-route.yaml
  - 06-networkpolicy.yaml
  - mysql
