apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "classic-models-api.mysqlLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
  {{- if .Values.mysql.storage.storageClassName }}
  storageClassName: {{ .Values.mysql.storage.storageClassName }}
  {{- end }}
