apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "classic-models-api.mysqlLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
  {{- if .Values.mysql.storage.storageClassName }}
  storageClassName: {{ .Values.mysql.storage.storageClassName }}
  {{- end }}
