apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: classic-models-api-allow-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "classic-models-api.apiLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: classic-models-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-allow-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "classic-models-api.mysqlLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mysql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: classic-models-api
      ports:
        - protocol: TCP
          port: 3306
